apiVersion: apps/v1
kind: Deployment

metadata:
  name: techtalksapi
  # namespace: voxxed-days-2018sg
  labels:
    run: techtalksapi

spec:
  replicas: 2
  selector:
    matchLabels:
      run: techtalksapi

  template:
    metadata:
      labels:
        run: techtalksapi
    spec:
      containers:
        - name: techtalksapi
          image: nileshgule/techtalksapi:rabbitmq-keda
          env:
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:8080
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
