apiVersion: v1
kind: Service

metadata:
  name: rabbitmq-producer-service
spec:
  type: LoadBalancer
  # type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http-default-port
      protocol: TCP
    - name: http-traffic
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    run: rabbitmq-producer    
