version: "3"

services:
  techtalks.api:
    image: nileshgule/techtalksapi:rabbitmq-keda
    build:
      context: src
      dockerfile: Dockerfile-TechTalksAPI

  techtalks.processor:
    image: nileshgule/techtalksconsumer:rabbitmq-keda
    build:
      context: src
      dockerfile: Dockerfile-TechTalksMQConsumer
