apiVersion: keda.k8s.io/v1alpha1
kind: TriggerAuthentication
metadata:
  name: trigger-auth-rabbitmq-host
spec:
  secretTargetRef:
  - parameter: host
    name: secrets-rabbitmq-host-connection
    key: rabbitmq-connectionstring